import { GoogleGenAI } from "@google/genai";

const API_KEY = import.meta.env.VITE_GEMINI_API_KEY;

if (!API_KEY) {
  console.warn("VITE_GEMINI_API_KEY environment variable is not set. Using default logic or placeholder.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY || "" });

/**
 * Generates an image from a topic with a specified aspect ratio.
 */
export const generateImageFromTopic = async (topic: string, aspectRatio: string): Promise<string> => {
  try {
    const enhancedPrompt = `
      Create a professional, visually stunning, and high-quality image for a social media post about the topic: "${topic}".
      The image should be abstract, conceptual, and metaphorical.
      Use a sophisticated and modern color palette.
      It must be suitable for a professional and corporate audience.
      ABSOLUTELY NO TEXT, letters, or numbers in the image.
      The style should be clean, minimalist, and elegant.
    `;

    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: enhancedPrompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/png',
        aspectRatio: aspectRatio,
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
      return `data:image/png;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No images were generated by the API.");
    }
  } catch (error) {
    console.error("Error generating image with Gemini API:", error);
    throw new Error("Failed to communicate with the image generation service.");
  }
};

/**
 * Generates social media post text from a topic.
 */
export const generatePostTextFromTopic = async (topic: string): Promise<string> => {
  try {
    const prompt = `
            You are an expert social media strategist specializing in creating engaging content for professional platforms.
            Given the topic: "${topic}", write a compelling and insightful post.

            The post should:
            1. Start with a strong hook to grab attention.
            2. Provide value, insight, or a thought-provoking perspective on the topic.
            3. Maintain a professional and inspiring tone.
            4. End with a call-to-action or a question to encourage engagement.
            5. Include 3-5 relevant and popular hashtags at the end.

            Format the output as clean, readable plain text. Do not use Markdown.
        `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });

    return response.text;
  } catch (error) {
    console.error("Error generating text with Gemini API:", error);
    throw new Error("Failed to communicate with the text generation service.");
  }
};
